[build]
  functions = "functions"
  command = """
cp functions/export/lib/* node_modules/canvas/build/Release/ && \
ls -la node_modules/canvas/build/Release/ && \
yarn build
"""

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["canvas", "lzma"]
  included_files = [
    "./functions/export/xhr-sync-worker.js",
    "./functions/export/lib/*",
    "./public/Cascadia.ttf",
    "./public/FG_Virgil.ttf",
  ]
