[build]
  functions = "functions"
  command = "yarn build"
  environment = { LD_LIBRARY_PATH = "" }

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["canvas", "lzma"]
  included_files = [
    "./functions/export/xhr-sync-worker.js",
    "./functions/export/lib/*",
    "./public/Cascadia.ttf",
    "./public/FG_Virgil.ttf",
  ]
